#!/bin/sh
#
# Pre-commit hook to run Checkstyle
#
BLUE='\033[0;34m'
NC='\033[0m' # No Color
info_message() {
    echo "${BLUE}Info: ${1}${NC}"
}

# Check if there are staged changes
if git diff --cached --quiet; then
    info_message "No staged changes to commit"
    exit 0
fi

# Run Checkstyle
mvn checkstyle:check

# Capture the result of the Checkstyle run
RESULT=$?

# If Checkstyle failed, do not commit
if [ $RESULT -ne 0 ]; then
    echo "Checkstyle failed. Please fix the issues before committing."
    exit 1
fi

# Allow the commit if Checkstyle passed
exit 0
