#!/bin/sh
#
# Pre-commit hook to run Checkstyle
#

# Run Checkstyle
mvn checkstyle:check

# Capture the result of the Checkstyle run
RESULT=$?

# If Checkstyle failed, do not commit
if [ $RESULT -ne 0 ]; then
    echo "Checkstyle failed. Please fix the issues before committing."
    exit 1
fi

# Allow the commit if Checkstyle passed
exit 0
